
INSERT INTO ROOM (ID, ROOM_NUMBER, NUMBER_OF_BEDS) VALUES (1,'1','1');
INSERT INTO ROOM (ID, ROOM_NUMBER, NUMBER_OF_BEDS) VALUES (2,'2','2');
INSERT INTO ROOM (ID, ROOM_NUMBER, NUMBER_OF_BEDS) VALUES (3,'3','3');
INSERT INTO ROOM (ID, ROOM_NUMBER, NUMBER_OF_BEDS) VALUES (4,'4','3');
INSERT INTO ROOM (ID, ROOM_NUMBER, NUMBER_OF_BEDS) VALUES (5,'5','4');

INSERT INTO PERSON (ID, NAME, SURNAME, EMAIL,PASSWORD,ROLE) VALUES (1,'John','Rambo','jr@gmail.com','password','USER');
INSERT INTO PERSON (ID, NAME, SURNAME, EMAIL,PASSWORD,ROLE) VALUES (2,'Zbigniew','Json','zj@gmail.com','password','USER');
INSERT INTO PERSON (ID, NAME, SURNAME, EMAIL,PASSWORD,ROLE) VALUES (3,'Beata','Byk','bb@gmail.com','password','USER');
INSERT INTO PERSON (ID, NAME, SURNAME, EMAIL,PASSWORD,ROLE) VALUES (4,'Maciej','Niechciał','mn@gmail.com','password','USER');
INSERT INTO PERSON (ID, NAME, SURNAME, EMAIL,PASSWORD,ROLE) VALUES (5,'Grzegorz','Kaczka','gk@gmail.com','password','ADMIN');

INSERT INTO RESERVATION(ID, START_RESREVATION_DATE, END_RESREVATION_DATE,PERSON_ID,ROOM_ID) values (1,parseDateTime('01/10/2020','DD/MM/YYYY'), parseDateTime('12/10/2020','DD/MM/YYYY'),1,1);
INSERT INTO RESERVATION(ID, START_RESREVATION_DATE, END_RESREVATION_DATE,PERSON_ID,ROOM_ID) values (2,parseDateTime('15/10/2020','DD/MM/YYYY'), parseDateTime('24/10/2020','DD/MM/YYYY'),2,1);
INSERT INTO RESERVATION(ID, START_RESREVATION_DATE, END_RESREVATION_DATE,PERSON_ID,ROOM_ID) values (3,parseDateTime('01/01/2020','DD/MM/YYYY'), parseDateTime('09/02/2020','DD/MM/YYYY'),3,3);
